In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['I dont know what to say','I do know what not to say','I guess I am bored','I am not bored but dont know that feeling'],'output':['1','0','0','1']})

In [3]:
df

text output
0                    I dont know what to say      1
1                  I do know what not to say      0
2                         I guess I am bored      0
3  I am not bored but dont know that feeling      1

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])

In [9]:
# vocab
print(cv.vocabulary_)

{'dont': 4, 'know': 7, 'what': 12, 'to': 11, 'say': 9, 'do': 3, 'not': 8, 'guess': 6, 'am': 0, 'bored': 1, 'but': 2, 'that': 10, 'feeling': 5}


In [13]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 0 0 1 0 0 1 0 1 0 1 1]]
[[0 0 0 1 0 0 0 1 1 1 0 1 1]]
[[1 1 0 0 0 0 1 0 0 0 0 0 0]]
[[1 1 1 0 1 1 0 1 1 0 1 0 0]]


In [16]:
cv.transform(['I know I know I know right']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0]])

In [ ]:
# Bag of words sucessfully handles the oov problem as we can see from the above code right is out of the vocabulary