In [83]:
import pandas as pd
import numpy as np

In [84]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [85]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [87]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [88]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [89]:
df.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [90]:
# drop unnecessary columns
df=df.drop(['Geography','Surname'],axis=1)

In [91]:
# creating the dummy varibles
df= pd.get_dummies(df,columns=['Gender'],drop_first=True)

In [92]:
df

RowNumber  CustomerId  CreditScore  Age  Tenure    Balance  \
0             1    15634602          619   42       2       0.00   
1             2    15647311          608   41       1   83807.86   
2             3    15619304          502   42       8  159660.80   
3             4    15701354          699   39       1       0.00   
4             5    15737888          850   43       2  125510.82   
...         ...         ...          ...  ...     ...        ...   
9995       9996    15606229          771   39       5       0.00   
9996       9997    15569892          516   35      10   57369.61   
9997       9998    15584532          709   36       7       0.00   
9998       9999    15682355          772   42       3   75075.31   
9999      10000    15628319          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0                 1          1               1        101348.88       1   
1                 1          0               1        112542.58       0   
2                 3          1               0        113931.57       1   
3                 2          0               0         93826.63       0   
4                 1          1               1         79084.10       0   
...             ...        ...             ...              ...     ...   
9995              2          1               0         96270.64       0   
9996              1          1               1        101699.77       0   
9997              1          0               1         42085.58       1   
9998              2          1               0         92888.52       1   
9999              1          1               0         38190.78       0   

      Gender_Male  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
9995            1  
9996            1  
9997            0  
9998            1  
9999            0  

[10000 rows x 12 columns]

In [93]:
# splitting the data
X =df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [94]:
# Standardizing the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X=scaler.fit_transform(X)


In [95]:
X

array([[-1.73187761, -0.78321342, -0.32622142, ...,  0.97024255,
         0.02188649,  1.97716468],
       [-1.7315312 , -0.60653412, -0.44003595, ...,  0.97024255,
         0.21653375, -0.50577476],
       [-1.73118479, -0.99588476, -1.53679418, ..., -1.03067011,
         0.2406869 ,  1.97716468],
       ...,
       [ 1.73118479, -1.47928179,  0.60498839, ...,  0.97024255,
        -1.00864308,  1.97716468],
       [ 1.7315312 , -0.11935577,  1.25683526, ..., -1.03067011,
        -0.12523071,  1.97716468],
       [ 1.73187761, -0.87055909,  1.46377078, ..., -1.03067011,
        -1.07636976, -0.50577476]])

In [105]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.3,random_state=1)

In [103]:
x_train

array([[-0.79864863,  0.42601595, -0.23310044, ...,  0.97024255,
         0.42879259, -0.50577476],
       [ 0.04867063, -1.01693224, -0.25379399, ..., -1.03067011,
        -1.02569751, -0.50577476],
       [-0.84229631,  1.18116742, -0.39864885, ...,  0.97024255,
        -0.94491882,  1.97716468],
       ...,
       [-1.41837641, -0.20820284,  0.22215769, ...,  0.97024255,
        -0.14019969,  1.97716468],
       [ 0.06668396, -1.15464451,  0.12903671, ...,  0.97024255,
         0.01875682, -0.50577476],
       [-1.65047122,  1.13933659,  1.16371428, ..., -1.03067011,
        -1.15858217,  1.97716468]])

In [104]:
y_train

array([1, 0, 0, ..., 0, 0, 1], dtype=uint8)

In [106]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [117]:
# Hyperparameter tuning
def build_model(hp):
  model=Sequential()

  counter=0
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if counter==0:
      model.add(Dense(
          hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
          activation=hp.Choice('activation'+str(i),values=['tanh','relu','sigmoid']),
          input_dim=11
      ))
    else:
        model.add(Dense(
          hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
          activation=hp.Choice('activation'+str(i),values=['tanh','relu','sigmoid'])
      ))
  counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['rmsprop','adam','sgd','adadelta']),loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [113]:
pip install -U keras-tuner

In [118]:
import kerastuner as kt
from kerastuner.tuners import RandomSearch

In [119]:
tuner = RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='my_dir',
    project_name='project'
)

In [120]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test),verbose=1)

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.5606666803359985

Best val_accuracy So Far: 0.5606666803359985
Total elapsed time: 00h 00m 04s


In [121]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 104,
 'activation0': 'relu',
 'optimizer': 'sgd',
 'units1': 96,
 'activation1': 'sigmoid',
 'units2': 16,
 'activation2': 'tanh',
 'units3': 8,
 'activation3': 'relu',
 'units4': 24,
 'activation4': 'sigmoid',
 'units5': 104,
 'activation5': 'sigmoid',
 'units6': 80,
 'activation6': 'sigmoid',
 'units7': 16,
 'activation7': 'tanh',
 'units8': 128,
 'activation8': 'tanh',
 'units9': 112,
 'activation9': 'sigmoid'}

In [122]:
model=tuner.get_best_models(num_models=1)[0]

In [123]:
model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test),initial_epoch=6)

Epoch 7/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6884 - accuracy: 0.5454 - val_loss: 0.6900 - val_accuracy: 0.5557
Epoch 8/100
219/219 [==============================] - 0s 2ms/step - loss: 0.6878 - accuracy: 0.5509 - val_loss: 0.6868 - val_accuracy: 0.5590
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.6873 - accuracy: 0.5527 - val_loss: 0.6854 - val_accuracy: 0.5600
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.6868 - accuracy: 0.5520 - val_loss: 0.6886 - val_accuracy: 0.5627
Epoch 11/100
219/219 [==============================] - 1s 2ms/step - loss: 0.6863 - accuracy: 0.5527 - val_loss: 0.6877 - val_accuracy: 0.5663
Epoch 12/100
219/219 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5610 - val_loss: 0.6848 - val_accuracy: 0.5600
Epoch 13/100
219/219 [==============================] - 0s 2ms/step - loss: 0.6857 - accuracy: 0.5630 - val_loss: 0.6843 - val_accuracy: 0.