In [1]:
import tensorflow as tf

Creating Tensors

In [3]:
string = tf.Variable('hello world',tf.string)
number = tf.Variable(22,tf.int32)
floating = tf.Variable(22.0,tf.float64)



Rank/Degree of Tensors

These terms simply means the number of dimensions involved in tensor.
The above tensors we created are basically of rank 0 because they are scalar which means they dont have dimension. scalars are dimensionless.

Now below cell represents the tensors of higer rank


In [7]:
# anything in array are basically of rank 1 , coz it can store more than 1 value in 1 dimension
rank1_tensor = tf.Variable(["akku","sonu","chinu"],tf.string)
rank1_tensor = tf.Variable([["akku"],["chinti"],["rohan bhai"]],tf.string)  # these are tensors of rank 2 coz list inside the list basically nested list

# important : we should have the uniform number of elements in the list.


to determine the rank of the tensor we can use the following method

In [8]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Shape of Tensors

The shape of a tensors basically means the number of elements in each dimension.
To get the shape we will use shape method.


In [10]:
rank1_tensor.shape

TensorShape([3, 1])

Changing the shape


In [12]:
tensor1=tf.ones([1,2,3]) # tf.ones creates the tensor of shape [1,2,3] full of ones
tensor2=tf.reshape(tensor1,[2,3,1])
tensor3=tf.reshape(tensor2,[3,-1])

In [13]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Types of tensors:

1. Variables
2. Constant
3. Placeholder
4. Sparse tensor

with the exception of variable all these tensors are immutable, meaning their value wont change during execution.